### ISSUE TITLE
Support spaces in template filenames

### ISSUE THREAD

**Issue by tonyarnold** [thoughtbot/liftoff#161]
If I define my Info.plist to be named `<%= project_name %> Prefix.pch` in my `.liftoffrc`, the scripts fail:

```
/usr/local/Cellar/liftoff/1.3/rubylib/liftoff/file_manager.rb:62:in `read': No such file or directory - /usr/local/Cellar/liftoff/1.3/templates/<%= project_name %> Info.plist (Errno::ENOENT)
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/file_manager.rb:62:in `move_template'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/file_manager.rb:38:in `create_template_file'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/file_manager.rb:18:in `generate'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:57:in `move_template'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:31:in `add_file'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:23:in `create_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:43:in `block (2 levels) in create_groups_for_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:42:in `each'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:42:in `block in create_groups_for_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:36:in `each_pair'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:36:in `create_groups_for_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:25:in `create_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:43:in `block (2 levels) in create_groups_for_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:42:in `each'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:42:in `block in create_groups_for_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:36:in `each_pair'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:36:in `create_groups_for_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:25:in `create_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:43:in `block (2 levels) in create_groups_for_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:42:in `each'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:42:in `block in create_groups_for_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:36:in `each_pair'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:36:in `create_groups_for_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:25:in `create_tree'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:11:in `block (2 levels) in create_project'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:10:in `each'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:10:in `block in create_project'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:9:in `each'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/project_builder.rb:9:in `create_project'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/launchpad.rb:45:in `generate_project'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/launchpad.rb:12:in `block in liftoff'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/file_manager.rb:5:in `chdir'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/file_manager.rb:5:in `create_project_dir'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/launchpad.rb:11:in `liftoff'
    from /usr/local/Cellar/liftoff/1.3/rubylib/liftoff/cli.rb:10:in `run'
    from /usr/local/bin/liftoff:14:in `<main>'
```

**Comment by Legoless** [comment]
This issue remains in 1.4.1, but may be tied to a different reason:

```
/usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/file_manager.rb:60:in `read': No such file or directory - /usr/local/Cellar/liftoff/1.4.1/templates/Development.Debug.xcconfig (Errno::ENOENT)
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/file_manager.rb:60:in `move_template'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/file_manager.rb:36:in `create_template_file'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/file_manager.rb:17:in `generate'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:58:in `move_template'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:32:in `add_file'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:24:in `create_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:44:in `block (2 levels) in create_groups_for_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:43:in `each'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:43:in `block in create_groups_for_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:37:in `each_pair'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:37:in `create_groups_for_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:26:in `create_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:44:in `block (2 levels) in create_groups_for_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:43:in `each'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:43:in `block in create_groups_for_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:37:in `each_pair'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:37:in `create_groups_for_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:26:in `create_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:44:in `block (2 levels) in create_groups_for_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:43:in `each'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:43:in `block in create_groups_for_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:37:in `each_pair'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:37:in `create_groups_for_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:26:in `create_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:44:in `block (2 levels) in create_groups_for_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:43:in `each'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:43:in `block in create_groups_for_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:37:in `each_pair'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:37:in `create_groups_for_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:26:in `create_tree'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:12:in `block (2 levels) in create_project'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:11:in `each'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:11:in `block in create_project'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:10:in `each'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/project_builder.rb:10:in `create_project'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/launchpad.rb:57:in `generate_project'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/launchpad.rb:15:in `block in liftoff'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/file_manager.rb:5:in `chdir'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/file_manager.rb:5:in `create_project_dir'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/launchpad.rb:14:in `liftoff'
	from /usr/local/Cellar/liftoff/1.4.1/rubylib/liftoff/cli.rb:10:in `run'
	from /usr/local/bin/liftoff:14:in `<main>'
```

Interesting thing is that ~/.liftoff/templates/ has that file and it has no space anywhere. Other custom files in .liftoffrc are added and they work, but this one apparently not.
