### ISSUE TITLE
Ability to add bridging-header

### ISSUE THREAD

**Issue by MattFriedman** [thoughtbot/liftoff#220]
It would be very useful if the tool could allow for at least one bridging-header.

If it can do this already please let me know how. 

Thanks for this very useful tool.

**Comment by adamhrz** [comment]
@MattFriedman You can add a custom .liftoffrc either in your iOSdev project folder or ~/.liftoffrc with an override:

```
app_target_templates:
  objc:
    - <%= project_name %>:
      - Categories:
      - Protocols:
      - Headers:
      - Models:
      - ViewModels:
      - Controllers:
        - <%= prefix %>AppDelegate.h
        - <%= prefix %>AppDelegate.m
      - Views:
      - Resources:
        - Images.xcassets
        - Storyboards:
          - Main.storyboard
        - Nibs:
          - LaunchScreen.xib
        - Other-Sources:
          - Info.plist
          - main.m
      - Supporting Files:
        - <%= project_name %>-Bridging-Header.h
```

**Comment by solrankos** [comment]
You also need to link to the bridging header in build settings. I can't get it to work in the 1.5 version though.
```
extra_config:  
    all:
        SWIFT_OBJC_BRIDGING_HEADER:
            - Resources/OtherSources/$(PROJECT_NAME)-Bridging-Header.h
```

**Comment by gfontenot** [comment]
@solrankos Weird, that looks like it should work to me. Do you know what the error is? It's possible that YAML is interpreting that last line as an Array instead of as a string. Maybe remove the leading `-`?

**Comment by solrankos** [comment]
@gfontenot 
Tried removing the dash but nothing happens. I get this error when i'm running liftoff.
````
Adding shell script build phase ''
/usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/template_finder.rb:22:in `join': no implicit conversion of nil into String (TypeError)
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/template_finder.rb:22:in `path_for_file'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/template_finder.rb:10:in `local_template'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/template_finder.rb:4:in `template_path'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/file_manager.rb:28:in `template_contents'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/xcodeproj_helper.rb:51:in `block in add_script_phases'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/xcodeproj_helper.rb:44:in `each'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/xcodeproj_helper.rb:44:in `add_script_phases'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/launchpad.rb:83:in `add_script_phases'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/launchpad.rb:43:in `perform_project_actions'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/launchpad.rb:20:in `block in liftoff'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/file_manager.rb:5:in `chdir'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/file_manager.rb:5:in `create_project_dir'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/launchpad.rb:14:in `liftoff'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/cli.rb:10:in `run'
	from /usr/local/bin/liftoff:14:in `<main>
````

**Comment by gfontenot** [comment]
That looks like a different error to me. It looks like you don't have a bridging header template set up.

**Comment by solrankos** [comment]
@gfontenot I have, in the created project i have all my files from the template. But none of my ```extra_config``` are set in build settings.

Here's an outtake from my rc:
```
extra_config:
    Debug:
        HOCKEY_APP_ID:
        GCC_PREPROCESSOR_DEFINITIONS:
            - $(inherited)
            - HOCKEY_APP_ID=$(HOCKEY_APP_ID)
           
    Release:
        HOCKEY_APP_ID:
            - 8b5edca942c706cbc04e8d7f36bd9338
        GCC_PREPROCESSOR_DEFINITIONS:
            - $(inherited)
            - HOCKEY_APP_ID=$(HOCKEY_APP_ID)

    all:
        SWIFT_OBJC_BRIDGING_HEADER:
            - Resources/OtherSources/$(PROJECT_NAME)-Bridging-Header.h
```

**Comment by solrankos** [comment]
Found the issue! i was doing this (working in version 1.4.1)
```
run_script_phases:
    - todo.sh: Warn for TODO and FIXME comments
    - xcres_build.sh: Generate constants file of resources, images, strings etc.
```
Which produced the error in previous comment and also ignored my ```extra_config:```

When i specified the ```run_script_phases:``` like below. everything worked out fine and i got my build settings :sunglasses: :+1: 
```
run_script_phases:
    - file: todo.sh
      name: Warn for TODO and FIXME comments
    - file: xcres_build.sh
      name: Generate constants file of resources, images, strings etc.
```

**Comment by gfontenot** [comment]
Ah, got it. That makes sense. Sorry for the red herring error warnings. We should probably do a better job with notifying of that syntax change.

**Comment by gfontenot** [comment]
@MattFriedman Does this solve your original issue?

**Comment by gfontenot** [comment]
I'm going to close this since it seems to be solved. If this is still needed or is still an issue please feel free to re-open or create a new issue.
