### ISSUE TITLE
Crash while creating new project

### ISSUE THREAD

**Issue by adamszeptycki** [thoughtbot/liftoff#240]
Hi,
I'm getting this stack trace every time I'm trying to create new project with liftoff. I tried using default liftoffrc - with exactly the same results.
```
Sending stats
Setting the project indentation level to 4
Setting warnings at the project level
Setting GCC_TREAT_WARNINGS_AS_ERRORS for Release builds
Adding shell script build phase ''
/usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/template_finder.rb:22:in `join': no implicit conversion of nil into String (TypeError)
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/template_finder.rb:22:in `path_for_file'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/template_finder.rb:10:in `local_template'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/template_finder.rb:4:in `template_path'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/file_manager.rb:28:in `template_contents'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/xcodeproj_helper.rb:51:in `block in add_script_phases'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/xcodeproj_helper.rb:44:in `each'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/xcodeproj_helper.rb:44:in `add_script_phases'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/launchpad.rb:83:in `add_script_phases'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/launchpad.rb:43:in `perform_project_actions'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/launchpad.rb:20:in `block in liftoff'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/file_manager.rb:5:in `chdir'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/file_manager.rb:5:in `create_project_dir'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/launchpad.rb:14:in `liftoff'
	from /usr/local/Cellar/liftoff/1.5.0/rubylib/liftoff/cli.rb:10:in `run'
	from /usr/local/bin/liftoff:14:in `<main>'
```

Any thoughts how to fix that problem? Is it an issue on my side?

**Comment by jakecraige** [comment]
Does this issue happen if you remove custom `.liftoffrc`?

Can you paste in what you're using as the `.liftoffrc`?

**Comment by adamszeptycki** [comment]
It does happen when I don't have custom `liftoffrc`.
My custom `lifoffrc` was exactly the same as: `https://github.com/thoughtbot/liftoff/blob/master/defaults/liftoffrc` with only my name specified:
```
author: "Adam Szeptycki"
```

**Comment by adamszeptycki** [comment]
I ended up having to remove all formulas from brew. After that I did install liftoff again and it worked. After that installed all formulas once again and everything is working fine right now.

**Comment by gfontenot** [comment]
Weird. Sorry you ran into problems, glad it's working better for you now.
